name: dartdos
description: DOS but Dart and in command prompt yes
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  dart_console: ^1.0.0
  http: ^0.13.3
  math_expressions: ^2.2.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
